### ISSUE TITLE
Sound Effect Disconnect

### ISSUE THREAD

**Issue by josephomorrow** [widelands/widelands#4258]
After saving the game, SoundHandler errors begin.

**To Reproduce**
1. Begin campaign
2. Run follow some instructions
3. Save game
4. Game sounds stop, while console screen continuous scrolls error messages

**Expected behavior**
Nothing should change after game saved.

**Screenshots**
n/a

**Version:**
 - Fedora 32
 - Widelands Version: 1.0~git1[c3fc079@master] (debug)

**Additional context**
Partial readout from console after saving game:

[00:06:41.974 real] ERROR: SoundHandler: Sound effect 7 does not exist!
[00:06:41.977 real] ERROR: SoundHandler: Sound effect 7 does not exist!
[00:06:41.977 real] ERROR: SoundHandler: Sound effect 6 does not exist!
[00:06:41.977 real] ERROR: SoundHandler: Sound effect 2 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 2 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 7 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!
[00:06:41.979 real] ERROR: SoundHandler: Sound effect 1 does not exist!

**Comment by gunchleoc** [comment]
Maybe related to https://github.com/widelands/widelands/commit/7f72ddfd870096f9d5e9dea44fc119fe21eeb3c1

**Comment by Niektory** [comment]
I've bisected and apparently the first bad commit is [e4cd8290e38140eef8be1b32c1d9678a5485dedd] Map preview on selection screen (#4201)

**Comment by Niektory** [comment]
This is the problem I think:

https://github.com/widelands/widelands/blob/01bc2e918e86aa81b4c1aaa3f15fee5b7d68d71b/src/logic/editor_game_base.cc#L86-L91
https://github.com/widelands/widelands/blob/01bc2e918e86aa81b4c1aaa3f15fee5b7d68d71b/src/wui/gamedetails.h#L72-L73
https://github.com/widelands/widelands/blob/01bc2e918e86aa81b4c1aaa3f15fee5b7d68d71b/src/wui/mapdetails.h#L60

**Comment by gunchleoc** [comment]
Fixed in https://github.com/widelands/widelands/pull/4240 so I won't have to fix this twice.

**Comment by josephomorrow** [comment]
Trying Widelands Version 1.0~git9[ec48524@master] (Debug)

Still getting endless SoundHandler errors after saving game. Also, after exiting:

==25895==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 152 byte(s) in 1 object(s) allocated from:
    #0 0x7ffa60998837 in __interceptor_calloc (/lib64/libasan.so.6+0xb0837)
    #1 0x7ffa5e87c7d5  (/lib64/libSDL2-2.0.so.0+0x847d5)

SUMMARY: AddressSanitizer: 152 byte(s) leaked in 1 allocation(s).

**Comment by gunchleoc** [comment]
The fix has not been merged to master yet - it's part of a big pull request (https://github.com/widelands/widelands/pull/4240) - I made an error with the link in my post above.

I always get 1 memory leak when I exit too - it's coming either from SDL or from the Mesa drivers, so there's nothing we can do about that one.

**Comment by josephomorrow** [comment]
Sorry. I'm still learning some of the steps in the process and what they are called. Trying to catch up with latest programming requirements so I can help more. Is this the place to ask you which text editor(s) you prefer when programming or troubleshooting?

**Comment by frankystone** [comment]
This happens also when starting the editor and loading a map.

**Comment by Niektory** [comment]
> Sorry. I'm still learning some of the steps in the process and what they are called. Trying to catch up with latest programming requirements so I can help more. Is this the place to ask you which text editor(s) you prefer when programming or troubleshooting?

I actually have no idea what would be the right place to ask this :-)
For C++ I use Code::Blocks. It makes it much easier to navigate a big codebase than a simple editor. It has some flaws though so there are likely better ones out there.
For everything else I use Mousepad, a simple editor that comes with Xfce.

**Comment by gunchleoc** [comment]
I use QTCreator for C++ and Geany for Lua/Python/Bash. I also use Geany for resolving merge conflicts in CMakeLists.txt files so that QTCreator can load the project.
